name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.17.0]

    steps:
    - uses: actions/checkout@v3
      with:
        ref: new

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        gulp clean build
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: AriaNg
        path: ./
